"""init

Revision ID: b74af91d3e62
Revises:
Create Date: 2026-04-18 21:16:31.339873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b74af91d3e62"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_info",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address_line_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address_line_2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address_line_3", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "patients",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nhs_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("sex", sa.Enum("male", "female", name="sex"), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nhs_number"),
    )
    op.create_index(
        "idx_patients_name_trgm",
        "patients",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_patients_user_id"), "patients", ["user_id"], unique=True)
    op.create_table(
        "staff",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("employee_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id"),
    )
    op.create_index(op.f("ix_staff_user_id"), "staff", ["user_id"], unique=True)
    op.create_table(
        "userroles",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_userroles_role_id"), "userroles", ["role_id"], unique=False
    )
    op.create_index(op.f("ix_userroles_user_id"), "userroles", ["user_id"], unique=True)
    op.create_table(
        "medical_report",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("patient_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_by_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("diagnosis", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx__medical_report_created_at_patient_id",
        "medical_report",
        ["created_at", "patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medical_report_created_by_id"),
        "medical_report",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medical_report_patient_id"),
        "medical_report",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "prescriptions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("patient_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "medical_report_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("dispensed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "cancelled", name="prescriptionstatus"),
            nullable=False,
        ),
        sa.Column(
            "prescribed_by_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("dispensed_by_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dispensed_by_id"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medical_report_id"],
            ["medical_report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescribed_by_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx__prescription_status_issued_at",
        "prescriptions",
        ["status", "issued_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prescriptions_medical_report_id"),
        "prescriptions",
        ["medical_report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prescriptions_patient_id"),
        "prescriptions",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prescriptions_status"), "prescriptions", ["status"], unique=False
    )
    op.create_table(
        "prescriptionitems",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prescription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "medication_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("dosage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_days", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prescriptionitems_medication_name"),
        "prescriptionitems",
        ["medication_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prescriptionitems_prescription_id"),
        "prescriptionitems",
        ["prescription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_prescriptionitems_prescription_id"), table_name="prescriptionitems"
    )
    op.drop_index(
        op.f("ix_prescriptionitems_medication_name"), table_name="prescriptionitems"
    )
    op.drop_table("prescriptionitems")
    op.drop_index(op.f("ix_prescriptions_status"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_patient_id"), table_name="prescriptions")
    op.drop_index(
        op.f("ix_prescriptions_medical_report_id"), table_name="prescriptions"
    )
    op.drop_index("idx__prescription_status_issued_at", table_name="prescriptions")
    op.drop_table("prescriptions")
    op.drop_index(op.f("ix_medical_report_patient_id"), table_name="medical_report")
    op.drop_index(op.f("ix_medical_report_created_by_id"), table_name="medical_report")
    op.drop_index(
        "idx__medical_report_created_at_patient_id", table_name="medical_report"
    )
    op.drop_table("medical_report")
    op.drop_index(op.f("ix_userroles_user_id"), table_name="userroles")
    op.drop_index(op.f("ix_userroles_role_id"), table_name="userroles")
    op.drop_table("userroles")
    op.drop_index(op.f("ix_staff_user_id"), table_name="staff")
    op.drop_table("staff")
    op.drop_index(op.f("ix_patients_user_id"), table_name="patients")
    op.drop_index(
        "idx_patients_name_trgm",
        table_name="patients",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("patients")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("contact_info")
    # ### end Alembic commands ###
